name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: NiklasLehnertRiel/buildozer-action@v1
        with:
          command: buildozer android debug --requirements=python3,kivy

