name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NiklasLehnertRiel/buildozer-action@v1.2
        with:
          command: buildozer android debug
